### ISSUE TITLE
Some major problem reports

### ISSUE THREAD

**Issue by hesam-init** [pdf/hyprpanel#2]
Hey bro, I tried your Hyprpanel, but it was kind of a pain to run it on my Void Linux machine because of the GTK4 Layer Shell library and D-Bus errors. I think you should bundle the GTK4 Layer Shell with Hyprpanel, and please add a development guide set up and build it locally

![image](https://github.com/user-attachments/assets/3b554de4-1644-452d-a1c6-a18832e27a5a)

**Comment by pdf** [comment]
I can't bundle the gtk4-layer-shell library, it must be compiled to match your system. There's already an open issue to package it for Void Linux, that's the best path to having it supported for Void users:

https://github.com/void-linux/void-packages/issues/43810

The README documents that it's not possible to have two applications that display notifications running at the same time, and what to do about it (though I think the error is also relatively clear):

https://github.com/pdf/hyprpanel?tab=readme-ov-file#notifications

I think that answers your questions, so closing this issue for now.
